
import { Language, Translations } from './types';

export const LANGUAGES: { code: Language, name: string }[] = [
  { code: 'zh-TW', name: '繁體中文' },
  { code: 'zh-CN', name: '简体中文' },
  { code: 'en', name: 'English' },
  { code: 'ja', name: '日本語' },
  { code: 'ko', name: '한국어' },
];

export const INTEREST_OPTIONS = ['food', 'history', 'shopping', 'nature', 'art'];

export const TRANSLATIONS: Record<Language, Translations> = {
  'zh-TW': {
    appName: '天生玩家',
    destination: '目的地',
    destinationPlaceholder: '例如：日本東京',
    duration: '旅遊天數',
    durationPlaceholder: '例如：5',
    arrivalTime: '抵達城市時間',
    startDate: '出發日期',
    interests: '興趣與關鍵字',
    generateItinerary: '生成行程',
    generating: '正在為您生成專屬行程...',
    interestOptions: {
      food: '美食',
      history: '歷史文化',
      shopping: '購物',
      nature: '自然景觀',
      art: '藝術',
    },
    welcomeMessage: '歡迎使用您的 AI 旅遊規劃師',
    welcomeSubMessage: '請輸入您的旅遊偏好，讓我們為您打造一段難忘的旅程。',
    loadingMessages: [
      '正在搜尋最佳景點...',
      '為您規劃完美的路線...',
      '尋找不容錯過的美食...',
      '打包當地文化小貼士...',
      '即將完成您的夢幻之旅...',
    ],
    dayPrefix: '第',
    daySuffix: '天',
    accommodationSuggestion: '住宿建議',
    generalTips: '注意事項與建議',
    errorTitle: '哎呀，出錯了！',
    errorSuggestion: '無法生成行程。請檢查您的輸入或稍後再試。如果問題持續存在，可能是 API 金鑰設定有誤。',
    language: '語言',
    copyright: '霍家私塾',
    viewOnGoogleMaps: '在 Google 地圖上查看',
    addContent: '追加內容與調整',
    addContentPlaceholder: '輸入您想增加或修改的行程，例如「增加一個適合小孩的行程」或「我想去吉卜力美術館」...',
    addContentButton: '更新行程',
    refiningItinerary: '正在為您更新行程...',
    export: '匯出',
    exportHTML: '匯出 HTML',
    exportWord: '匯出 Word',
    uploadDraft: '或上傳行程初稿',
    uploadDraftDescription: '支援 .txt, .md, .doc, .docx, .pdf 檔案',
    startOver: '重新開始',
    newTrip: '新旅程',
    tripHistory: '歷史紀錄',
    noHistory: '尚無歷史紀錄。',
    deleteTrip: '刪除此行程',
    suggestions: '建議',
    viewMap: '查看當日地圖路線',
    estimatedBudget: '總預算估算',
    customInterestPlaceholder: '新增關鍵字 (例如: 迪士尼樂園)',
    addInterest: '新增',
    generatingImage: '正在生成旅行代表圖片...',
    nearbyRecommendations: '周邊推薦',
    recommendationTypes: {
        attraction: '景點',
        food: '美食',
        shopping: '購物',
    },
    generalTipCategories: {
      etiquette: "禮儀",
      cashAndCards: "現金與信用卡",
      businessHours: "營業時間",
      holidays: "節日注意",
      transportation: "交通",
      wifi: "手機/Wi-Fi",
      reservations: "體驗預約",
      trash: "禮節與垃圾",
      weatherAndAttire: "天氣與穿著",
    }
  },
  'zh-CN': {
    appName: '天生玩家',
    destination: '目的地',
    destinationPlaceholder: '例如：日本东京',
    duration: '旅游天数',
    durationPlaceholder: '例如：5',
    arrivalTime: '抵达城市时间',
    startDate: '出发日期',
    interests: '兴趣与关键字',
    generateItinerary: '生成行程',
    generating: '正在为您生成专属行程...',
    interestOptions: {
      food: '美食',
      history: '历史文化',
      shopping: '购物',
      nature: '自然景观',
      art: '艺术',
    },
    welcomeMessage: '欢迎使用您的 AI 旅游规划师',
    welcomeSubMessage: '请输入您的旅游偏好，让我们为您打造一段难忘的旅程。',
    loadingMessages: [
      '正在搜寻最佳景点...',
      '为您规划完美的路线...',
      '寻找不容错过的美食...',
      '打包当地文化小贴士...',
      '即将完成您的梦幻之旅...',
    ],
    dayPrefix: '第',
    daySuffix: '天',
    accommodationSuggestion: '住宿建议',
    generalTips: '注意事项与建议',
    errorTitle: '哎呀，出错了！',
    errorSuggestion: '无法生成行程。请检查您的输入或稍后再试。如果问题持续存在，可能是 API 密钥设定有误。',
    language: '语言',
    copyright: '霍家私塾',
    viewOnGoogleMaps: '在 Google 地图上查看',
    addContent: '追加内容与调整',
    addContentPlaceholder: '输入您想增加或修改的行程，例如「增加一个适合小孩的行程」或「我想去吉卜力美术馆」...',
    addContentButton: '更新行程',
    refiningItinerary: '正在为您更新行程...',
    export: '导出',
    exportHTML: '导出 HTML',
    exportWord: '导出 Word',
    uploadDraft: '或上传行程初稿',
    uploadDraftDescription: '支持 .txt, .md, .doc, .docx, .pdf 文件',
    startOver: '重新开始',
    newTrip: '新旅程',
    tripHistory: '历史纪录',
    noHistory: '暂无历史纪录。',
    deleteTrip: '删除此行程',
    suggestions: '建议',
    viewMap: '查看当日地图路线',
    estimatedBudget: '总预算估算',
    customInterestPlaceholder: '新增关键字 (例如: 迪士尼乐园)',
    addInterest: '新增',
    generatingImage: '正在生成旅行代表图片...',
    nearbyRecommendations: '周边推荐',
    recommendationTypes: {
        attraction: '景点',
        food: '美食',
        shopping: '购物',
    },
    generalTipCategories: {
      etiquette: "礼仪",
      cashAndCards: "现金与信用卡",
      businessHours: "营业时间",
      holidays: "节日注意",
      transportation: "交通",
      wifi: "手机/Wi-Fi",
      reservations: "体验预约",
      trash: "礼节与垃圾",
      weatherAndAttire: "天气与穿着",
    }
  },
  'en': {
    appName: 'Born Player',
    destination: 'Destination',
    destinationPlaceholder: 'e.g., Tokyo, Japan',
    duration: 'Duration (days)',
    durationPlaceholder: 'e.g., 5',
    arrivalTime: 'Arrival Time',
    startDate: 'Start Date',
    interests: 'Interests & Keywords',
    generateItinerary: 'Generate Itinerary',
    generating: 'Generating your itinerary...',
    interestOptions: {
      food: 'Food',
      history: 'History & Culture',
      shopping: 'Shopping',
      nature: 'Nature',
      art: 'Art',
    },
    welcomeMessage: 'Welcome to Your AI Travel Planner',
    welcomeSubMessage: 'Enter your preferences to create an unforgettable journey.',
    loadingMessages: [
      'Searching for the best attractions...',
      'Planning the perfect route...',
      'Finding must-try local delicacies...',
      'Packing in cultural tips...',
      'Finalizing your dream trip...',
    ],
    dayPrefix: 'Day',
    daySuffix: '',
    accommodationSuggestion: 'Accommodation Suggestion',
    generalTips: 'Tips & Suggestions',
    errorTitle: 'Oops, something went wrong!',
    errorSuggestion: 'Could not generate an itinerary. Please check your inputs or try again.',
    language: 'Language',
    copyright: 'Huo Family Private School',
    viewOnGoogleMaps: 'View on Google Maps',
    addContent: 'Add & Adjust Content',
    addContentPlaceholder: 'e.g., "add a kid-friendly activity" or "I want to go to the Ghibli Museum"...',
    addContentButton: 'Update Itinerary',
    refiningItinerary: 'Updating itinerary...',
    export: 'Export',
    exportHTML: 'Export HTML',
    exportWord: 'Export Word',
    uploadDraft: 'Or upload a draft',
    uploadDraftDescription: 'Supports .txt, .md, .doc, .docx, .pdf files',
    startOver: 'Start Over',
    newTrip: 'New Trip',
    tripHistory: 'History',
    noHistory: 'No saved trips yet.',
    deleteTrip: 'Delete this trip',
    suggestions: 'Suggestions',
    viewMap: "View Day's Route on Map",
    estimatedBudget: 'Estimated Total Budget',
    customInterestPlaceholder: 'Add keyword (e.g., Disneyland)',
    addInterest: 'Add',
    generatingImage: 'Generating trip image...',
    nearbyRecommendations: 'Nearby Recommendations',
    recommendationTypes: {
        attraction: 'Attraction',
        food: 'Food',
        shopping: 'Shopping',
    },
    generalTipCategories: {
      etiquette: "Etiquette",
      cashAndCards: "Cash & Credit Cards",
      businessHours: "Business Hours",
      holidays: "Holidays",
      transportation: "Transportation",
      wifi: "Mobile / Wi-Fi",
      reservations: "Reservations",
      trash: "Etiquette & Trash",
      weatherAndAttire: "Weather & Attire",
    }
  },
  'ja': {
    appName: '天生玩家',
    destination: '目的地',
    destinationPlaceholder: '例：東京、日本',
    duration: '旅行日数',
    durationPlaceholder: '例：5',
    arrivalTime: '都市到着時間',
    startDate: '出発日',
    interests: '興味・キーワード',
    generateItinerary: '日程を作成',
    generating: '旅行プランを作成中...',
    interestOptions: {
      food: 'グルメ',
      history: '歴史・文化',
      shopping: 'ショッピング',
      nature: '自然',
      art: 'アート',
    },
    welcomeMessage: 'AIトラベルプランナーへようこそ',
    welcomeSubMessage: '旅行の好みを入力し、忘れられない旅を計画しましょう。',
    loadingMessages: [
      '最高の観光スポットを検索中...',
      '完璧なルートを計画中...',
      '見逃せないグルメを探しています...',
      '現地の文化に関するヒントを収集中...',
      '夢の旅行がまもなく完成します...',
    ],
    dayPrefix: '',
    daySuffix: '日目',
    accommodationSuggestion: '宿泊施設の提案',
    generalTips: '注意事項とアドバイス',
    errorTitle: 'エラーが発生しました！',
    errorSuggestion: '日程を作成できませんでした。入力を確認するか、後でもう一度お試しください。',
    language: '言語',
    copyright: '霍家私塾',
    viewOnGoogleMaps: 'Googleマップで表示',
    addContent: '内容の追加と調整',
    addContentPlaceholder: '例：「子供向けのアクティビティを追加」「ジブリ美術館に行きたい」...',
    addContentButton: '日程を更新',
    refiningItinerary: '日程を更新しています...',
    export: 'エクスポート',
    exportHTML: 'HTMLでエクスポート',
    exportWord: 'Wordでエクスポート',
    uploadDraft: 'または下書きをアップロード',
    uploadDraftDescription: '.txt、.md、.doc、.docx、.pdf ファイルに対応',
    startOver: 'やり直す',
    newTrip: '新しい旅',
    tripHistory: '履歴',
    noHistory: 'まだ履歴はありません。',
    deleteTrip: 'この日程を削除',
    suggestions: '提案',
    viewMap: 'その日のルートを地図で見る',
    estimatedBudget: '旅行全体の総予算目安',
    customInterestPlaceholder: 'キーワードを追加 (例: ディズニーランド)',
    addInterest: '追加',
    generatingImage: '旅行の代表画像を生成中...',
    nearbyRecommendations: '周辺のおすすめ',
    recommendationTypes: {
        attraction: '観光スポット',
        food: 'グルメ',
        shopping: 'ショッピング',
    },
    generalTipCategories: {
      etiquette: "マナー",
      cashAndCards: "現金とクレジットカード",
      businessHours: "営業時間",
      holidays: "祝日",
      transportation: "交通手段",
      wifi: "携帯・Wi-Fi",
      reservations: "予約",
      trash: "マナーとゴミ",
      weatherAndAttire: "天気と服装",
    }
  },
  'ko': {
    appName: '본 플레이어',
    destination: '목적지',
    destinationPlaceholder: '예: 일본 도쿄',
    duration: '여행 기간 (일)',
    durationPlaceholder: '예: 5',
    arrivalTime: '도시 도착 시간',
    startDate: '출발일',
    interests: '관심사 및 키워드',
    generateItinerary: '여행 일정 생성',
    generating: '일정을 생성 중입니다...',
    interestOptions: {
      food: '음식',
      history: '역사 및 문화',
      shopping: '쇼핑',
      nature: '자연',
      art: '예술',
    },
    welcomeMessage: 'AI 여행 플래너에 오신 것을 환영합니다',
    welcomeSubMessage: '여행 취향을 입력하여 잊지 못할 여행을 만들어 보세요.',
    loadingMessages: [
      '최고의 명소를 검색 중...',
      '완벽한 경로를 계획 중...',
      '놓칠 수 없는 현지 음식을 찾는 중...',
      '현지 문화 팁을 담는 중...',
      '꿈의 여행을 마무리하는 중...',
    ],
    dayPrefix: '',
    daySuffix: '일차',
    accommodationSuggestion: '숙소 추천',
    generalTips: '팁 및 제안',
    errorTitle: '오류가 발생했습니다!',
    errorSuggestion: '일정을 생성할 수 없습니다. 입력을 확인하거나 나중에 다시 시도해 주세요.',
    language: '언어',
    copyright: '곽가 사숙',
    viewOnGoogleMaps: 'Google 지도에서 보기',
    addContent: '내용 추가 및 조정',
    addContentPlaceholder: '예: "어린이에게 적합한 활동 추가" 또는 "지브리 미술관에 가고 싶어요"...',
    addContentButton: '일정 업데이트',
    refiningItinerary: '일정을 업데이트하는 중...',
    export: '내보내기',
    exportHTML: 'HTML로 내보내기',
    exportWord: 'Word로 내보내기',
    uploadDraft: '또는 초안 업로드',
    uploadDraftDescription: '.txt, .md, .doc, .docx, .pdf 파일 지원',
    startOver: '다시 시작',
    newTrip: '새로운 여행',
    tripHistory: '기록',
    noHistory: '아직 저장된 여행이 없습니다.',
    deleteTrip: '이 여행 삭제',
    suggestions: '제안',
    viewMap: '오늘의 경로를 지도에서 보기',
    estimatedBudget: '예상 총 경비',
    customInterestPlaceholder: '키워드 추가 (예: 디즈니랜드)',
    addInterest: '추가',
    generatingImage: '여행 대표 이미지 생성 중...',
    nearbyRecommendations: '주변 추천',
    recommendationTypes: {
        attraction: '명소',
        food: '음식',
        shopping: '쇼핑',
    },
    generalTipCategories: {
      etiquette: "예절",
      cashAndCards: "현금 및 신용카드",
      businessHours: "영업 시간",
      holidays: "공휴일",
      transportation: "교통",
      wifi: "모바일 / 와이파이",
      reservations: "예약",
      trash: "예절 및 쓰레기",
      weatherAndAttire: "날씨 및 복장",
    }
  },
};
